/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        popover: "var(--popover)",
        "popover-foreground": "var(--popover-foreground)",
        primary: "var(--primary)",
        "primary-foreground": "var(--primary-foreground)",
        secondary: "var(--secondary)",
        "secondary-foreground": "var(--secondary-foreground)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        accent: "var(--accent)",
        "accent-foreground": "var(--accent-foreground)",
        destructive: "var(--destructive)",
        "destructive-foreground": "var(--destructive-foreground)",
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",

        cvBg: "var(--cvBg)",
        cvBgSoft: "var(--cvBgSoft)",
        cvBgMuted: "var(--cvBgMuted)",
        cvBorder: "var(--cvBorder)",
        cvText: "var(--cvText)",
        cvMutedText: "var(--cvMutedText)",
        cvAccent: "var(--cvAccent)",
        cvAccentSoft: "var(--cvAccentSoft)",
        cvAccentDeep: "var(--cvAccentDeep)",
        cvButton: "var(--cvButton)",
        cvButtonHover: "var(--cvButtonHover)",
        cvTagline: "var(--cvTagline)",
        cvCardBorder: "var(--cvCardBorder)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
